package org.kgusarov.krono

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings
import java.time.ZoneId
import java.time.ZoneOffset

@SuppressFBWarnings("MS_EXPOSE_REP")
object TimezoneAbbreviations {
    @JvmStatic
    val TIMEZONE_ABBR_MAP: Map<String, ZoneId> =
        mapOf(
            "ACDT" to ZoneOffset.ofHoursMinutes(10, 30),
            "ACST" to ZoneOffset.ofHoursMinutes(9, 30),
            "ADT" to ZoneOffset.ofHours(-3),
            "AEDT" to ZoneOffset.ofHours(11),
            "AEST" to ZoneOffset.ofHours(10),
            "AFT" to ZoneOffset.ofHoursMinutes(4, 30),
            "AKDT" to ZoneOffset.ofHours(-8),
            "AKST" to ZoneOffset.ofHours(-9),
            "ALMT" to ZoneOffset.ofHours(6),
            "AMST" to ZoneOffset.ofHours(-3),
            "AMT" to ZoneOffset.ofHours(-4),
            "ANAST" to ZoneOffset.ofHours(12),
            "ANAT" to ZoneOffset.ofHours(12),
            "AQTT" to ZoneOffset.ofHours(5),
            "ART" to ZoneOffset.ofHours(-3),
            "AST" to ZoneOffset.ofHours(-4),
            "AWDT" to ZoneOffset.ofHours(9),
            "AWST" to ZoneOffset.ofHours(8),
            "AZOST" to ZoneOffset.ofHours(0),
            "AZOT" to ZoneOffset.ofHours(-1),
            "AZST" to ZoneOffset.ofHours(5),
            "AZT" to ZoneOffset.ofHours(4),
            "BNT" to ZoneOffset.ofHours(8),
            "BOT" to ZoneOffset.ofHours(-4),
            "BRST" to ZoneOffset.ofHours(-2),
            "BRT" to ZoneOffset.ofHours(-3),
            "BST" to ZoneOffset.ofHours(1),
            "BTT" to ZoneOffset.ofHours(6),
            "CAST" to ZoneOffset.ofHours(8),
            "CAT" to ZoneOffset.ofHours(2),
            "CCT" to ZoneOffset.ofHoursMinutes(6, 30),
            "CDT" to ZoneOffset.ofHours(-5),
            "CEST" to ZoneOffset.ofHours(2),
            "CHADT" to ZoneOffset.ofHoursMinutes(13, 45),
            "CHAST" to ZoneOffset.ofHoursMinutes(12, 45),
            "CKT" to ZoneOffset.ofHours(-10),
            "CLST" to ZoneOffset.ofHours(-3),
            "CLT" to ZoneOffset.ofHours(-4),
            "COT" to ZoneOffset.ofHours(-5),
            "CST" to ZoneOffset.ofHours(-6),
            "CT" to ZoneId.of("America/Chicago"),
            "CVT" to ZoneOffset.ofHours(-1),
            "CXT" to ZoneOffset.ofHours(7),
            "ChST" to ZoneOffset.ofHours(10),
            "DAVT" to ZoneOffset.ofHours(7),
            "EASST" to ZoneOffset.ofHours(-5),
            "EAST" to ZoneOffset.ofHours(-6),
            "EAT" to ZoneOffset.ofHours(3),
            "ECT" to ZoneOffset.ofHours(-5),
            "EDT" to ZoneOffset.ofHours(-4),
            "EEST" to ZoneOffset.ofHours(3),
            "EET" to ZoneOffset.ofHours(2),
            "EGST" to ZoneOffset.ofHours(0),
            "EGT" to ZoneOffset.ofHours(-1),
            "EST" to ZoneOffset.ofHours(-5),
            "ET" to ZoneId.of("America/New_York"),
            "FJST" to ZoneOffset.ofHours(13),
            "FJT" to ZoneOffset.ofHours(12),
            "FKST" to ZoneOffset.ofHours(-3),
            "FKT" to ZoneOffset.ofHours(-4),
            "FNT" to ZoneOffset.ofHours(-2),
            "GALT" to ZoneOffset.ofHours(-6),
            "GAMT" to ZoneOffset.ofHours(-9),
            "GET" to ZoneOffset.ofHours(4),
            "GFT" to ZoneOffset.ofHours(-3),
            "GILT" to ZoneOffset.ofHours(12),
            "GST" to ZoneOffset.ofHours(4),
            "GYT" to ZoneOffset.ofHours(-4),
            "HAA" to ZoneOffset.ofHours(-3),
            "HAC" to ZoneOffset.ofHours(-5),
            "HADT" to ZoneOffset.ofHours(-9),
            "HAE" to ZoneOffset.ofHours(-4),
            "HAP" to ZoneOffset.ofHours(-7),
            "HAR" to ZoneOffset.ofHours(-6),
            "HAST" to ZoneOffset.ofHours(-10),
            "HAT" to ZoneOffset.ofHours(-2),
            "HAY" to ZoneOffset.ofHours(-8),
            "HKT" to ZoneOffset.ofHours(8),
            "HLV" to ZoneOffset.ofHours(-3),
            "HNA" to ZoneOffset.ofHours(-4),
            "HNC" to ZoneOffset.ofHours(-6),
            "HNE" to ZoneOffset.ofHours(-5),
            "HNP" to ZoneOffset.ofHours(-8),
            "HNR" to ZoneOffset.ofHours(-7),
            "HNT" to ZoneOffset.ofHoursMinutes(-2, -30),
            "HNY" to ZoneOffset.ofHours(-9),
            "HOVT" to ZoneOffset.ofHours(7),
            "ICT" to ZoneOffset.ofHours(7),
            "IDT" to ZoneOffset.ofHours(3),
            "IOT" to ZoneOffset.ofHours(6),
            "IRDT" to ZoneOffset.ofHoursMinutes(4, 30),
            "IRKST" to ZoneOffset.ofHours(9),
            "IRKT" to ZoneOffset.ofHours(8),
            "IRST" to ZoneOffset.ofHoursMinutes(3, 30),
            "IST" to ZoneOffset.ofHoursMinutes(5, 30),
            "JST" to ZoneOffset.ofHours(9),
            "KGT" to ZoneOffset.ofHours(6),
            "KRAST" to ZoneOffset.ofHours(8),
            "KRAT" to ZoneOffset.ofHours(8),
            "KST" to ZoneOffset.ofHours(9),
            "KUYT" to ZoneOffset.ofHours(4),
            "LHDT" to ZoneOffset.ofHours(11),
            "LHST" to ZoneOffset.ofHoursMinutes(10, 30),
            "LINT" to ZoneOffset.ofHours(14),
            "MAGST" to ZoneOffset.ofHours(12),
            "MAGT" to ZoneOffset.ofHours(12),
            "MART" to ZoneOffset.ofHoursMinutes(-8, -30),
            "MAWT" to ZoneOffset.ofHours(5),
            "MDT" to ZoneOffset.ofHours(-6),
            "MESZ" to ZoneOffset.ofHours(2),
            "MEZ" to ZoneOffset.ofHours(1),
            "MHT" to ZoneOffset.ofHours(12),
            "MMT" to ZoneOffset.ofHoursMinutes(6, 30),
            "MSD" to ZoneOffset.ofHours(4),
            "MSK" to ZoneOffset.ofHours(3),
            "MST" to ZoneOffset.ofHours(-7),
            "MT" to ZoneId.of("Canada/Mountain"),
            "MUT" to ZoneOffset.ofHours(4),
            "MVT" to ZoneOffset.ofHours(5),
            "MYT" to ZoneOffset.ofHours(8),
            "NCT" to ZoneOffset.ofHours(11),
            "NDT" to ZoneOffset.ofHoursMinutes(-1, -30),
            "NFT" to ZoneOffset.ofHoursMinutes(11, 30),
            "NOVT" to ZoneOffset.ofHours(6),
            "NPT" to ZoneOffset.ofHoursMinutes(5, 45),
            "NST" to ZoneOffset.ofHoursMinutes(-2, -30),
            "NUT" to ZoneOffset.ofHours(-11),
            "NZDT" to ZoneOffset.ofHours(13),
            "NZST" to ZoneOffset.ofHours(12),
            "OMSST" to ZoneOffset.ofHours(7),
            "OMST" to ZoneOffset.ofHours(7),
            "PDT" to ZoneOffset.ofHours(-7),
            "PET" to ZoneOffset.ofHours(-5),
            "PETST" to ZoneOffset.ofHours(12),
            "PETT" to ZoneOffset.ofHours(12),
            "PGT" to ZoneOffset.ofHours(10),
            "PHOT" to ZoneOffset.ofHours(13),
            "PHT" to ZoneOffset.ofHours(8),
            "PKT" to ZoneOffset.ofHours(5),
            "PMDT" to ZoneOffset.ofHours(-2),
            "PMST" to ZoneOffset.ofHours(-3),
            "PONT" to ZoneOffset.ofHours(11),
            "PST" to ZoneOffset.ofHours(-8),
            "PT" to ZoneId.of("America/Los_Angeles"),
            "PWT" to ZoneOffset.ofHours(9),
            "PYST" to ZoneOffset.ofHours(-3),
            "PYT" to ZoneOffset.ofHours(-4),
            "RET" to ZoneOffset.ofHours(4),
            "SAMT" to ZoneOffset.ofHours(4),
            "SAST" to ZoneOffset.ofHours(2),
            "SBT" to ZoneOffset.ofHours(11),
            "SCT" to ZoneOffset.ofHours(4),
            "SGT" to ZoneOffset.ofHours(8),
            "SRT" to ZoneOffset.ofHours(-3),
            "SST" to ZoneOffset.ofHours(-11),
            "TAHT" to ZoneOffset.ofHours(-10),
            "TFT" to ZoneOffset.ofHours(5),
            "TJT" to ZoneOffset.ofHours(5),
            "TKT" to ZoneOffset.ofHours(13),
            "TLT" to ZoneOffset.ofHours(9),
            "TMT" to ZoneOffset.ofHours(5),
            "TVT" to ZoneOffset.ofHours(12),
            "ULAT" to ZoneOffset.ofHours(8),
            "UYST" to ZoneOffset.ofHours(-2),
            "UYT" to ZoneOffset.ofHours(-3),
            "UZT" to ZoneOffset.ofHours(5),
            "VET" to ZoneOffset.ofHoursMinutes(-3, -30),
            "VLAST" to ZoneOffset.ofHours(11),
            "VLAT" to ZoneOffset.ofHours(11),
            "VUT" to ZoneOffset.ofHours(11),
            "WAST" to ZoneOffset.ofHours(2),
            "WAT" to ZoneOffset.ofHours(1),
            "WEST" to ZoneOffset.ofHours(1),
            "WESZ" to ZoneOffset.ofHours(1),
            "WET" to ZoneOffset.ofHours(0),
            "WEZ" to ZoneOffset.ofHours(0),
            "WFT" to ZoneOffset.ofHours(12),
            "WGST" to ZoneOffset.ofHours(-2),
            "WGT" to ZoneOffset.ofHours(-3),
            "WIB" to ZoneOffset.ofHours(7),
            "WIT" to ZoneOffset.ofHours(9),
            "WITA" to ZoneOffset.ofHours(8),
            "WST" to ZoneOffset.ofHours(14),
            "WT" to ZoneOffset.ofHours(0),
            "YAKST" to ZoneOffset.ofHours(10),
            "YAKT" to ZoneOffset.ofHours(10),
            "YAPT" to ZoneOffset.ofHours(10),
            "YEKST" to ZoneOffset.ofHours(6),
            "YEKT" to ZoneOffset.ofHours(6),
        )
}
